server:
  port: 8099
spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:3306/kx-app?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: ams2020
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  #redis和datasource是同一级
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  #mongodb连接配置
  data:
    mongodb:
      uri: mongodb://MongoDB:MongoDB@127.0.0.1:27017
      database: kx-app
  #rabbitmq连接配置
  rabbitmq:
    host: 192.168.1.101
    port: 5672
    username: admin
    password: 123456
    virtual-host: douyin-red-book
  #配置服务名
#  application:
#    name: douyin-red-book-nacos
  #配置nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # nacos 所在的地址
# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*'

# MinIO 配置
minio:
  endpoint: http://192.168.1.101:9000      # MinIO服务地址 这里的端口不是自己配置的端口?
  fileHost: http://192.168.1.101:9000      # 文件地址host 这里的端口不是自己配置的端口?
  bucketName: panpan                      # 存储桶bucket名称
  accessKey: ROOT                         # 用户名
  secretKey: 12345678                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m